### ISSUE TITLE
`las` and `ylab` does not work

### ISSUE THREAD

**Issue by mmahmoudian** [TomKellyGenetics/vioplot#1]
It seems the arguments `las` and `ylab` are not implemented in the package. I do not get any error/warning but they do not work either.

**Comment by TomKellyGenetics** [comment]
What input format are you using (e.g., list or formulae)? I will try to reproduce the issue to fix it.

**Comment by TomKellyGenetics** [comment]
I've investigated this and `xlab` and `ylab` are display IF a title is given with `main`. I will look into resolving this. In the meantime, setting `main=""` as a workaround will remove it. You can also set `yaxt="n"` and run `title` and `axis` separately (this was previously necessary with plotting on a log-scale but I've removed the need for this).

At the moment some `par` parameters such as `las` are not supported but I will look into adding them in a future release.

**Comment by TomKellyGenetics** [comment]
This is resolved in the development version on branch `dev`. All graphical parameters are passed to `vioplot.default`. If not given, values in `par()` are used. This should be consistent with parameters in `plot()`. Axes labels for formula input have also been changed, these now default to variable names (in addition to resolving factor levels #2).

**Comment by TomKellyGenetics** [comment]
This has been implemented in release 0.3.2 submitted to CRAN
