### ISSUE TITLE
Titles axes and position of legend in violin plots

### ISSUE THREAD

**Issue by Frauke-Hellwig** [TomKellyGenetics/vioplot#12]
1) The titles or names of the axis are not properly overwritten when I use  the code
title(xlab = "Species in Iris table", ylab = "Sepal Length in iris table"), but the original names of the axes are still there! What can I do to have them properly removed.

2) Sometimes it would be very helpful to have the legend OUTSIDE the actual plotting area, e.g. under the x-axis or right to the plotting area. I see only options where it is inside it. If you have other data than the example from iris, the legend can hide (part of) the violins, which is not nice. In the example I put the legend on the left bottom to show what I mean. You don't see the first violin now. 

How to have the legend OUTSIDE the polling area? 

Here is the code that produced the plot below.:
`
library(vioplot)

iris_large <- iris[iris$Sepal.Width > mean(iris$Sepal.Width), ]
iris_small <- iris[iris$Sepal.Width <= mean(iris$Sepal.Width), ]

vioplot(Sepal.Length~Species, data=iris_large, 
           col = "palevioletred", 
           plotCentre = "line", side = "right")

vioplot(Sepal.Length~Species, data=iris_small, 
            col = "lightblue", 
            plotCentre = "line", side = "left", add = T)

title(xlab = "Species in Iris table", ylab = "Sepal Length in iris table")

legend("bottomleft", fill = c("lightblue", "palevioletred"), 
       legend = c("small according to iris table", "large according to iris table"), 
       title = "Sepal Width as classified in iris table")
`

![image](https://user-images.githubusercontent.com/66963196/84681609-ac2cd180-af34-11ea-833e-3d107c8faeb5.png)

**Comment by TomKellyGenetics** [comment]
Hi Frauke,

Thanks, the example helps to understand your issue.

I think no changes to the source code are needed (you should be able to do this with the CRAN or `master` version). This stems from issues with "base R" plotting functions. Legend in particular can be tricky. As the axes labels are computed internally for `vioplot.formula` they're being called twice here. Legends can be especially tricky to work with (see the links for details on how to do this).

You can over-ride these with `xlab` and `ylab` arguments in the function, either with the input you desire or as `xlab = "", ylab = ""` to have them blank. I hope these examples help to solve your problem.

```{r}
library(vioplot)

iris_large <- iris[iris$Sepal.Width > mean(iris$Sepal.Width), ]
iris_small <- iris[iris$Sepal.Width <= mean(iris$Sepal.Width), ]

#title in vioplot call
vioplot(Sepal.Length~Species, data=iris_large,
        col = "palevioletred",
        plotCentre = "line", side = "right",
        xlab = "Species in Iris table", ylab = "Sepal Length in iris table")
vioplot(Sepal.Length~Species, data=iris_small,
        col = "lightblue",
        plotCentre = "line", side = "left", add = T)
legend("topright", fill = c("lightblue", "palevioletred"),
       legend = c("S", "L"),
       cex = 0.8, ncol = 1, inset=c(-0.05,0), xpd = TRUE, bty = "n")
````
![Rplot](https://user-images.githubusercontent.com/5493325/84720726-cb217700-afb9-11ea-8981-d0fcbd79c4b8.png)

```{r}
#title disabled in vioplot call and called afterwards
vioplot(Sepal.Length~Species, data=iris_large,
        col = "palevioletred",
        plotCentre = "line", side = "right",
        xlab = "", ylab = "")
vioplot(Sepal.Length~Species, data=iris_small,
        col = "lightblue",
        plotCentre = "line", side = "left", add = T)
title(xlab = "Species in Iris table", ylab = "Sepal Length in iris table")
legend("bottomright", fill = c("lightblue", "palevioletred"),
       legend = c("small according to iris table", "large according to iris table"),
       title = "Sepal Width as classified in iris table",
       cex = 0.8, ncol = 1, inset = 0:1, xpd = TRUE, bty = "n")
```
![Rplot01](https://user-images.githubusercontent.com/5493325/84720746-dc6a8380-afb9-11ea-8316-4f677c0281bc.png)

```
#title disabled in vioplot call and called afterwards
vioplot(Sepal.Length~Species, data=iris_large,
        col = "palevioletred",
        plotCentre = "line", side = "right",
        xlab = "", ylab = "")
vioplot(Sepal.Length~Species, data=iris_small,
        col = "lightblue",
        plotCentre = "line", side = "left", add = T)
title(xlab = "Species in Iris table", ylab = "Sepal Length in iris table")
legend("bottomleft", fill = c("lightblue", "palevioletred"),
       legend = c("small according to iris table", "large according to iris table"),
       title = "Sepal Width as classified in iris table",
       cex = 0.8, ncol = 1, inset = c(0, -0.25), xpd = TRUE, bty = "n")
```

![Rplot03](https://user-images.githubusercontent.com/5493325/84720812-07ed6e00-afba-11ea-8e50-7d642e09d097.png)

You may need to adjust the parameters in `legend` to fit the margins. More examples here:

https://benfradet.github.io/blog/2014/04/30/Display-legend-outside-plot-R
https://stackoverflow.com/questions/3932038/plot-a-legend-outside-of-the-plotting-area-in-base-graphics/3932558
https://coders-corner.net/2016/03/06/data-visualization-in-r-show-legend-outside-of-the-plotting-area/
http://dr-k-lo.blogspot.com/2014/03/the-simplest-way-to-plot-legend-outside.html

Tschüss!

**Comment by Frauke-Hellwig** [comment]
Hi Tim,

many thanks for your fast help. Your explanation was down to the point and really helped me solving my problems and to better understand how things work. I do like the split violin plots a lot, they are very informative, as you can see so much in a single plot at the same time. Many thanks for developing this R package. 

Ciao
