### ISSUE TITLE
Feature Request: histogram instead of density kernel

### ISSUE THREAD

**Issue by Jadamso** [TomKellyGenetics/vioplot#15]
Thank you for a great package.

For some cases, it would be helpful to use a histogram rather than a kernel density. The ability to use R's `hist` function and `breaks` argument would be very easy to use. This functionality is also not currently available via `ggplot`.

**Comment by TomKellyGenetics** [comment]
Thanks for the suggestion, this requires a significant overhaul of the source code but I agree it would be possible to use this package a foundation to implement this. I'm unsure whether it is best to set up a new parameter with an "if" statement or if it is better to create a new function for back-to-back histograms. The "split" parameter would also allow for bihistograms to be created in R.

I'm open to accepting pull requests if you have time to implement this yourself.

**Comment by TomKellyGenetics** [comment]
Addressed in open PR #18
