### ISSUE TITLE
Vioplot not working when formula categories are numbers

### ISSUE THREAD

**Issue by ekstroem** [TomKellyGenetics/vioplot#3]
Trying to plot two parallel violin plots using the formula interface. Here's a minimal example and the (surprising) outcome:

```
library("vioplot")
DF <- data.frame(x=c(rnorm(500),  rnorm(250, mean=-1, sd=.6), rnorm(250, mean=1, sd=.6)), group=factor(rep(1:2, times=c(500, 500))))
vioplot(x ~ group, data=DF)
```

which produces this result

![Screen Shot 2019-08-30 at 14 09 32](https://user-images.githubusercontent.com/6160801/64019624-f40e7380-cb2f-11e9-80f2-61aa25f5af31.png)

I'm fairly sure the problem is caused by the last line of vioplot.formula

    expression(vioplot( 1, 2 , xlab = xlab, ylab = ylab, names = names, ...))

Since the categories are named the numbers 1 and 2, they are parsed as numbers by `vioplot.default` and not as the labels referencing the data in the `datas` column. As far as I can see the default is not easily modified since the first two arguments are also used as the actual labels in the plot.

**Comment by TomKellyGenetics** [comment]
As a workaround, please use factors as text. I will consider if this can be addressed in a future release.

    library("vioplot")
    DF <- data.frame(x=c(rnorm(500),  rnorm(250, mean=-1, sd=.6), rnorm(250, mean=1, sd=.6)), group=factor(rep(c("A", "B"), times=c(500, 500))))
    vioplot(x ~ group, data=DF, names = 1:2)

![Rplot](https://user-images.githubusercontent.com/5493325/68259768-2089c300-007e-11ea-854e-6f9a08ec4d09.png)

**Comment by TomKellyGenetics** [comment]
Formula input has been updated in the `dev` branch this will be available in the next minor release.

`devtools::install_github("TomKellyGenetics/vioplot", ref = "dev")`
