### ISSUE TITLE
cex passed as argument is ignored

### ISSUE THREAD

**Issue by Derek-Jones** [TomKellyGenetics/vioplot#5]
`vioplot(stuff, cex =0.9)` does not have the desired effect, while
```
par(cex=0.9)
vioplot(stuff)
```
works fine.

Will report issues here, now I know about the github repro (it's not listed on CRAN)

**Comment by TomKellyGenetics** [comment]
Minor release 0.3.3 (submitted to CRAN) will resolve this. 

https://github.com/TomKellyGenetics/vioplot/releases/tag/0.3.3

**Comment by lillefrog** [comment]
I still have this problem. 

par(cex=0.9)
vioplot(stuff)

Changes the default text size

vioplot(cex=3, stuff)

Changes only the size of symbol marking the median

Example code:

`par(cex=1.5)
#plot(1:10, 1:10, col=1:10, pch=19, cex=8, xlab="", ylab="")


vioplot(iris$Sepal.Length[iris$Species=="setosa"], 
        iris$Sepal.Length[iris$Species=="versicolor"], 
        iris$Sepal.Length[iris$Species=="virginica"], 
        names=c("setosa", "versicolor", "virginica"),
        cex = 4.0)`
