### ISSUE TITLE
Option to change the color of the center line

### ISSUE THREAD

**Issue by Derek-Jones** [TomKellyGenetics/vioplot#8]
There is no option to change the color of the center line, running down the middle of the violin.

If you don't want to add another option, then perhaps make it the same as the border color?

**Comment by mmahmoudian** [comment]
Is this what you are looking for?

```
vioplot(iris[, 1:3], lineCol = "red")
```

![image](https://user-images.githubusercontent.com/390889/75759339-0a46f780-5d3e-11ea-869b-62802fa2ac49.png)


I think it worth mentioning how I found it:
line 417 and 419 of the `vioplot.R`file

**Comment by Derek-Jones** [comment]
Yes,  it is now working for me.

I am going blind, senile, or there is some kind of state dependency (see next bug report).

**Comment by mmahmoudian** [comment]
@Derek-Jones  so should this issue be closed?

**Comment by Derek-Jones** [comment]
Yes.  I cannot get it to fail.  So the problem is either my eyesight or something hard to duplicate.

**Comment by TomKellyGenetics** [comment]
At the moment, it is not possible to change colours of the box outline and whiskers separately. Is this what you are suggesting?

**Comment by Derek-Jones** [comment]
mmahmoudian 'solved' the problem (i.e., my eyesight) in an earlier comment.

**Comment by TomKellyGenetics** [comment]
I'll close this for now. Of course, issues with documentation are also helpful if it is unclear how to do this.
