### ISSUE TITLE
Global state being set by the arguments: xlog=TRUE, horizontal=TRUE

### ISSUE THREAD

**Issue by Derek-Jones** [TomKellyGenetics/vioplot#9]
> `vioplot(sample(40), xlog=TRUE, horizontal=TRUE)`
> `vioplot(sample(40))`
Error in plot.window(xlim, ylim, log = log, asp = asp, bty = bty, cex = cex,  : 
  "log=" specification must be character

A `vioplot(sample(40), ylog=FALSE)` makes the message go away

**Comment by TomKellyGenetics** [comment]
```
vioplot(sample(40), xlog=FALSE, horizontal = TRUE)
vioplot(sample(40), xlog=FALSE, horizontal = FALSE)
vioplot(sample(40), ylog=FALSE, horizontal = TRUE)
vioplot(sample(40), ylog=FALSE, horizontal = FALSE)
vioplot(sample(40), xlog=TRUE)
vioplot(sample(40), xlog=FALSE)
vioplot(sample(40), ylog=TRUE)
vioplot(sample(40), ylog=FALSE)
```

I've tried the above combinations. This is the only one to return an error:

```
 vioplot(sample(40), xlog=TRUE)
```
>Error in plot.window(xlim, ylim, log = log, asp = asp, bty = bty, cex = cex,  : 
  "log=" specification must be character 
>3.
>plot.window(xlim, ylim, log = log, asp = asp, bty = bty, cex = cex, 
>   xaxs = xaxs, yaxs = yaxs, lab = lab, mai = mai, mar = mar, 
>   mex = mex, mfcol = mfcol, mfrow = mfrow, mfg = mfg, xlog = xlog, 
>    ylog = ylog) at vioplot.R#381
>2.
>vioplot.default(sample(40), xlog = TRUE) at vioplot.R#145
>1.
>vioplot(sample(40), xlog = TRUE)

**Comment by Derek-Jones** [comment]
Try the two lines listed.

Just tried again, and got the same error on a different (Linux) machine.

**Comment by TomKellyGenetics** [comment]
I don't get this issue in the development version. As far as I'm aware,  `vioplot` does not change global variables (no use of `<<-`), it only takes elements of `par()` as inputs, it does not change them. What you're seeing is a bug with how log parameters are handled for horizontal plots. I think this is fixed now :)

**Comment by TomKellyGenetics** [comment]
@Derek-Jones I don't get this error on Mac OS but have reproduced it on a Linux server. I've checked that the development version installs from GitHub and doesn't give the same error. I've added unit tests for this and build passes on Travis CI. I'll close this and merge into master.
